//
// Created by Michal Ziobro on 01/08/2016.
//

#ifndef REMOTECONTROLLERAPI_SERVER_CONFIG_H
#define REMOTECONTROLLERAPI_SERVER_CONFIG_H

#define DEBUG 1

#endif //REMOTECONTROLLERAPI_SERVER_CONFIG_H
